### ISSUE TITLE
Sign in page not loading correctly

### ISSUE THREAD

**Issue by natalian98** [canonical/identity-platform-login-ui#247]
The login logic is currently tied to hydra. If you try to go to `/ui/reset_password` without a session, you'll get redirected to sign in but the page will be shown as loading:
![image](https://github.com/canonical/identity-platform-login-ui/assets/97316813/e364c132-f3ab-4900-b4de-2b95ff122a65)

This is due to missing `login_challenge` parameter value. Similar bug can be observed when going directly to http://localhost:4455/ui/login.

**Comment by nsklikas** [comment]
Not sure if this is what causes the bug or not, but in mulitple places in the frontend we are checking if the response from the backend contains a `request_url` (and sometimes we even redirect the user there), eg try to go to https://iam.dev.canonical.com/stg-identity-jaas-dev-login-ui/ui/reset_password. I thought we caught those on review, but it looks like some of these changes went through.

From a quick search:
- https://github.com/canonical/identity-platform-login-ui/blob/2357551f634c9be6986260366f1a5f391ae6f210/ui/pages/reset_password.tsx#L54
- https://github.com/canonical/identity-platform-login-ui/blob/2357551f634c9be6986260366f1a5f391ae6f210/ui/pages/reset_email.tsx#L40
- https://github.com/canonical/identity-platform-login-ui/blob/2357551f634c9be6986260366f1a5f391ae6f210/ui/pages/setup_secure.tsx#L50
- https://github.com/canonical/identity-platform-login-ui/blob/2357551f634c9be6986260366f1a5f391ae6f210/ui/pages/setup_passkey.tsx#L46
- https://github.com/canonical/identity-platform-login-ui/blob/2357551f634c9be6986260366f1a5f391ae6f210/ui/pages/setup_backup_codes.tsx#L46

I am pretty sure that this is not correct, but I am not sure what these checks are trying to accomplish. In a production environment all these are pointing to admin APIs, which are not exposed to the public internet. The `request_url` is the URL that the backend used to call Kratos, there is no reason to call the same URL from the frontend.

**Comment by edlerd** [comment]
I think this will be fixed as soon as https://github.com/canonical/identity-platform-login-ui/issues/281 is resolved.
