### ISSUE TITLE
No redirection on first login

### ISSUE THREAD

**Issue by nsklikas** [canonical/identity-platform-login-ui#275]
By deploying the bundle found on https://github.com/canonical/iam-bundle/pull/273, if I create an admin account through the kratos juju cli (`juju run kratos/0 create-admin-account email=a@b.com password=123a username=aba`) and I try to login via Hydra, I will be asked to register my authenticator and then I will end up in the `setup_complete` page instead of being redirected back to Hydra.

**Comment by lukasSerelis** [comment]
It'd be best from UX point of view to add a confirmation screen before the automatic redirect to the application. So the flow should be something like this:
![image](https://github.com/user-attachments/assets/e1d5ff66-1cc6-4c78-8aaa-83d5064d91b1)
Or in screens it would be 

1. Trying to sign in for the first time 
![image](https://github.com/user-attachments/assets/52504d4e-98fa-4c9c-a099-f62b60b85e15)

2. Required TOTP setup
![image](https://github.com/user-attachments/assets/f0a45d61-421a-4f63-85bc-f82df47a081e)

3. Setup complete, message to confirm that action has been successful (also good place to show any errors if some occur). And automatic redirect within 3 seconds.
![image](https://github.com/user-attachments/assets/0c465c23-4f3b-40b0-a2be-de46d6851228)

4. Landing on the 3rd party application page
![image](https://github.com/user-attachments/assets/e1786701-b989-4485-b2cf-e295d6476b3c)
