### ISSUE TITLE
Unknown error code on invalid totp

### ISSUE THREAD

**Issue by nsklikas** [canonical/identity-platform-login-ui#276]
If I try to input a otp that does not have the right length (6), then I get this error:
![image](https://github.com/user-attachments/assets/cf7e13af-e09a-458c-90c8-c6ce678245d1)

**Comment by natalian98** [comment]
https://www.ory.sh/docs/kratos/concepts/ui-user-interface#length-must-be--5-but-got-3-4000003

**Comment by nsklikas** [comment]
Since we have an exhaustive list of errors, shouldn't we create a mapping for the ones that make sense and just return `Server Error` for the rest?
