### ISSUE TITLE
Sign in with security key not working if email is cached

### ISSUE THREAD

**Issue by lukasSerelis** [canonical/identity-platform-login-ui#290]
**What is happening**
If you try to sign in but don't complete MFA and visit the initial sign in page again, it caches the email and only shows password and security key sign up options, even if security key is not set up. If the security key is not set up it's not putting an error message, it just keep redirecting back to the same page. 

**What should happen**
First of all it shouldn't obscure the email address that is cached, it's bad UX practice as the user might be trying to sign in to a different account, and you're making them guess which email has been cached. Display the email even thought it's been cached. Secondly, either display all methods of sign in or only supported ones, cause now you're doing neither.

**Preferred flow**
![image](https://github.com/user-attachments/assets/ad3475c0-e5dc-4115-b281-b921ac9804bb)

**Flow in screens**
1) User visits resource that is accessible via Login UI. UI displays all of possible sign in methods
![image](https://github.com/user-attachments/assets/991026ac-77c8-4a10-92a5-345f6cc08253)

2) User signs in with email and password. Login UI asks for MFA. User closes the tab
![image](https://github.com/user-attachments/assets/faa52a20-c429-49d5-93ed-555b0685b0d3)

3) User visits resource that is accessible via Login UI. UI displays cached email with ability to edit email, and all sign in methods that this email is able to use (in this example, email has security key and google, but not Okta set up for this identity.)
![image](https://github.com/user-attachments/assets/431bff60-b86f-4af4-b21e-888a6c3d8b3b)

**Compromise option**
Same flow, but display all of the possible sign in option, regardless of what options are possible. 
![image](https://github.com/user-attachments/assets/724e2743-9c15-4bb7-b282-d72afef5a6a0)

**Comment by nsklikas** [comment]
I don't really like the approach we take here:
- the button that says `Change e-mail`, seems weird/counter-intuitive to me as a user. 
- The logic for resetting aal1 feels very hacky and I think will be difficult for someone who does not have our context to extend.
- Even though we ask the user to provide their password, this is not needed. The session is cached in the cookies (we can just redirect them to the 2fa page.

We should have a look at what major providers do and copy them. For example on github (not the best example, I know) if you press back on the authorizer screen, you will be asked to enter your username/password again and if you do browser forward, you will again will be asked for totp.

I think for us the best flow would one of the following:
- show the user a message that says something along the lines `Please validate that this is you: {email}` and underneath 2 buttons (one for accepting and one for declining). If they decline, then we delete the user session and we show the login screen as well. If they accept, then we set the aal param to `aal=aal2` in the query param. This will show the user the totp page again.
- Do something similar to github and automatically reset the session and clear both fields, this would need some more work as we would want to keep the forward button working as well.

What do you think? cc @lukasSerelis @edlerd

_Originally posted by @nsklikas in https://github.com/canonical/identity-platform-login-ui/pull/292#pullrequestreview-2337635863_

**Comment by lukasSerelis** [comment]
> I don't really like the approach we take here:
> 
> * the button that says `Change e-mail`, seems weird/counter-intuitive to me as a user.
> * The logic for resetting aal1 feels very hacky and I think will be difficult for someone who does not have our context to extend.
> * Even though we ask the user to provide their password, this is not needed. The session is cached in the cookies (we can just redirect them to the 2fa page.
> 
> We should have a look at what major providers do and copy them. For example on github (not the best example, I know) if you press back on the authorizer screen, you will be asked to enter your username/password again and if you do browser forward, you will again will be asked for totp.
> 
> I think for us the best flow would one of the following:
> 
> * show the user a message that says something along the lines `Please validate that this is you: {email}` and underneath 2 buttons (one for accepting and one for declining). If they decline, then we delete the user session and we show the login screen as well. If they accept, then we set the aal param to `aal=aal2` in the query param. This will show the user the totp page again.
> * Do something similar to github and automatically reset the session and clear both fields, this would need some more work as we would want to keep the forward button working as well.
> 
> What do you think? cc @lukasSerelis @edlerd
> 
> _Originally posted by @nsklikas in [#292 (review)](https://github.com/canonical/identity-platform-login-ui/pull/292#pullrequestreview-2337635863)_

The github option is probably less fussy. Even if we don't have the browser forward action working it is a less convoluted flow. The change email and caching email is a thing a lot of SSOs do as well, so this isn't necessarily a unique flow. But I agree that it'd be simpler to just clear all fields. More frustrating in some cases, but less complex, and I'll always lean to less complexity. I'll update the flows to match this and then we can go forward with the github style of not saving either field imho.

**Comment by lukasSerelis** [comment]
![image](https://github.com/user-attachments/assets/fa370955-8e1b-4cad-a328-3263459a4556)
@nsklikas @edlerd 

Flow that I agree with Nikos is much more simplified. Nothing is cached. The only thing is a question of implementation if we can make it work but would be nice is the going forward in browser after going back to see working MFA again...

**Comment by edlerd** [comment]
> Flow that I agree with Nikos is much more simplified. Nothing is cached. The only thing is a question of implementation if we can make it work but would be nice is the going forward in browser after going back to see working MFA again...

Kratos is controlling which flow will be rendered. For a user coming with a kratos session, kratos initiates the "Enter password" with immutable email flow. I have no idea how to change this behaviour other than removing the cookie. Doing that automatically in the frontend -- without user interaction, as the flows suggest -- seems very hacky to me. Happy for other suggestions, maybe you can configure kratos accordingly?

**Comment by nsklikas** [comment]
I don't know about the possible kratos configurations off the top of my head (probably others are more suitable in answering that). But worst case possible we could handle this in the backend. There are 2 options:
- Enhancing the createLoginFlow endpoint, with a new parameter that would clear the kratos cookies. In this case the UI will just have to send the refresh parameter to the backend
- Create a new endpoint that would call the kratos endpoint that clears a session, if the frontend sees that the user has an active session with aal1 and they are at the password page, then the frontend will just call the backend to clear the session. 

Both of these should be possible, but I will have to validate it.

**Comment by edlerd** [comment]
@nsklikas I think this has been fixed with #301 
Can this be closed?

**Comment by nsklikas** [comment]
I think so, but I would leave it up to @lukasSerelis to decide

**Comment by edlerd** [comment]
Closing after talking to Lukas and he agreed.
