### ISSUE TITLE
MFA screens

### ISSUE THREAD

**Issue by lukasSerelis** [canonical/identity-platform-login-ui#293]
Some issues with MFA screens. Currently if a user selects to verify identity with backup code it doesn't offer a way to change it to use Authenticator app instead. Also some error message text issues. 
Ideally the flow should be like this: 
![image](https://github.com/user-attachments/assets/56d46121-bec5-49ac-8521-4a8dd2241748)

Or in screens:
1) User signs in
![image](https://github.com/user-attachments/assets/8a8f3816-2a30-40eb-86a9-0a07f49741c9)

2) Both Authenticator app and Backup code is set up
![image](https://github.com/user-attachments/assets/09a832db-6e90-4123-a67d-ea12f550208c)

3) If a user click I want to use a backup code, we take them to this page, which shows the ability to go back to using authenticator app.
![image](https://github.com/user-attachments/assets/559eacad-e1dc-45d3-8f99-46bc5a7ca511)

4) [Future cases] In a case where we support more methods for MFA than backup codes and TOTP, we should say "Use another method" and give users a selection like this
![image](https://github.com/user-attachments/assets/45d6838e-3a73-493f-bca1-0225fe6d877b)
![image](https://github.com/user-attachments/assets/513939d6-59a6-4449-907b-4d51d88cd503)

**Comment by nsklikas** [comment]
I don't think we should treat lookup secrets as a an alternative to the authenticator app. They are a fallback and should be used only if needed. Creation of lookup secrets usually requires aal2 or higher (see https://pages.nist.gov/800-63-3-Implementation-Resources/63B/Authenticators/, https://www.ory.sh/docs/kratos/mfa/lookup-secrets). So you shouldn't be able to create backup codes without a registered authenticator (unless you use your email?).

**Comment by lukasSerelis** [comment]
> I don't think we should treat lookup secrets as a an alternative to the authenticator app. They are a fallback and should be used only if needed. Creation of lookup secrets usually requires aal2 or higher (see https://pages.nist.gov/800-63-3-Implementation-Resources/63B/Authenticators/, https://www.ory.sh/docs/kratos/mfa/lookup-secrets). So you shouldn't be able to create backup codes without a registered authenticator (unless you use your email?).
Good shout, I'll upgrade the flow diagram to not have the case of using Backup codes as an alternative to authenticator app, will just be a fallback!
