### ISSUE TITLE
Backup codes do not download

### ISSUE THREAD

**Issue by lukasSerelis** [canonical/identity-platform-login-ui#314]
Clicking download button does nothing. Everything else works. [Chromium browser]
![image](https://github.com/user-attachments/assets/426e9265-09d4-4fb3-aa01-cbf31aef4dbd)

**Comment by natalian98** [comment]
@edlerd could you check it please? I remember that used to work well, it possibly broke after some refactoring

**Comment by edlerd** [comment]
sure, checking

**Comment by edlerd** [comment]
This is due to the content security policy introduced in #299 being too strict.
