### ISSUE TITLE
Overwritten `return_to` url when MFA setup must be enforced before backup codes check

### ISSUE THREAD

**Issue by natalian98** [canonical/identity-platform-login-ui#316]
If the user has 3 or less backup codes left, (s)he should be presented with a “Regenerate backup codes” screen and offered to regenerate the codes or continue to sign in:
![image](https://github.com/user-attachments/assets/eb7efa56-eb1f-4704-825f-002d31ffbb82)

However, if the user has no totp authenticator linked, in the above case the user will be first redirected to set it up (see [here](https://github.com/canonical/identity-platform-login-ui/blob/dd604ec001b4be1bc826bbb59fa75cd4970968bb/pkg/kratos/handlers.go#L238)) and after doing so, redirected to `/ui/setup_complete` without ever going to the backup codes screen.

It is a minor bug but may require admin intervention if the user doesn't end up adding totp and all the backup codes are eventually used.

I think the issue is both in frontend and backend:
- if MFA setup is enforced, we redirect to `setup_secure` and return without getting to [this](https://github.com/canonical/identity-platform-login-ui/blob/dd604ec001b4be1bc826bbb59fa75cd4970968bb/pkg/kratos/handlers.go#L242) check.
- the latter `return_to` is overwritten [here](https://github.com/canonical/identity-platform-login-ui/blob/dd604ec001b4be1bc826bbb59fa75cd4970968bb/ui/pages/setup_secure.tsx#L89) and is always forcing the redirection to `setup_complete` page.

**Comment by nsklikas** [comment]
The `setup_complete` page is supposed to fetch the `return_to` from the flow and redirect the user there after a short period of time. I think that the issue was always there and the backend should handle it, although it is not clear to me right now how that should be done (maybe we could over-ride the return_to of the login flow with one to regenerate the codes and then return the user to the original return_to)

**Comment by BarcoMasile** [comment]
> * if MFA setup is enforced, we redirect to `setup_secure` and return without getting to [this](https://github.com/canonical/identity-platform-login-ui/blob/dd604ec001b4be1bc826bbb59fa75cd4970968bb/pkg/kratos/handlers.go#L242) check.
> * the latter `return_to` is overwritten [here](https://github.com/canonical/identity-platform-login-ui/blob/dd604ec001b4be1bc826bbb59fa75cd4970968bb/ui/pages/setup_secure.tsx#L89) and is always forcing the redirection to `setup_complete` page.

What if we perform the backup code check before the mfa one?
Could that help?
@natalian98

**Comment by natalian98** [comment]
> What if we perform the backup code check before the mfa one? Could that help? @natalian98

Yes, that works as well. Thanks for pointing out an easy solution
