### ISSUE TITLE
Reset password flow not working and UI improvements

### ISSUE THREAD

**Issue by lukasSerelis** [canonical/identity-platform-login-ui#322]
When trying to reset password it doesn't complete the flow. Occasionally also the text-field is showing an error in field which is incorrect.
![image](https://github.com/user-attachments/assets/b79d1071-074b-4a2b-a764-b13590555efe)

On UI side, back button needs to be there, and Submit button needs to say "Reset password". Error message says "Invalid email address" should say "Incorrect email address"
![image](https://github.com/user-attachments/assets/d08de8a2-2ec4-47f4-8154-31b5627f6124)

If possible, when we can actually get to the success screen, it'd be great to validate which email address was submitted.
![image](https://github.com/user-attachments/assets/05ec4bc7-f298-4b0e-a635-f4dae580484c)

**Comment by natalian98** [comment]
Linked to https://github.com/canonical/identity-platform-login-ui/issues/315

**Comment by natalian98** [comment]
@edlerd could you also
- add the back button (it should just redirect to the login url)
- rename `Submit` to `Reset password`
- refactor the "Check your email" screen to contain the email address typed in the previous step
- make sure the field doesn't show the error message once you click on the button?
![image](https://github.com/user-attachments/assets/c32c6e59-85b4-4548-83f8-b20617767a8f)

**Comment by lukasSerelis** [comment]
Check your email step was not the right approach because the email doesn't contain the link to the page to enter that code to. instead, lets redirect to this link with the place to enter the code
![image](https://github.com/user-attachments/assets/adac6a73-2c80-4d45-ab25-bbca4ce2f029)

Followed by either success screen, or incorrect code error. In case of success screen, would be ideal if we could redirect the user back to the initial login screen to access the resource.

Error screen:
![image](https://github.com/user-attachments/assets/fcfe12fd-818d-417c-adc2-ba519d38a954)

Success flow:
![image](https://github.com/user-attachments/assets/ca3b3a02-9ea1-491a-a167-966906a8af84)
(after 5s)
![image](https://github.com/user-attachments/assets/41bea7e0-96ce-47b0-aa05-f26c8a5d9652)
