### ISSUE TITLE
TOTP setup UI 

### ISSUE THREAD

**Issue by lukasSerelis** [canonical/identity-platform-login-ui#324]
Current UI isn't ideal due to mental load presented. There is at the same time QR code, text code and entry field. Ideally we'd either have more seperation or hide the secret behind another screen.

Scenario 1, hiding one-time code secret thing behind a link:
1) Default screen.
![image](https://github.com/user-attachments/assets/f9daf4f5-1279-4aca-8cea-aa0fcd1a7ba0)
https://www.figma.com/design/zstuCMdHsKx8Wr9ERZx9Kw/Login-updates-(passkey%2C-MFA%2C-org-links)?node-id=166-8979&node-type=frame&t=GzhBGn7sxcZeBrJj-11

2) If you click can't scan code you see this. Clicking use QR instead takes you to default screen
![image](https://github.com/user-attachments/assets/27b764ff-032b-4626-8485-5b317b9fd061)
https://www.figma.com/design/zstuCMdHsKx8Wr9ERZx9Kw/Login-updates-(passkey%2C-MFA%2C-org-links)?node-id=235-5519&node-type=frame&t=GzhBGn7sxcZeBrJj-11

Scenario 2:
Show the one-time code secret but better separate them better
![image](https://github.com/user-attachments/assets/fb31b146-f5ad-4a1a-b4f6-abb392d273a9)
https://www.figma.com/design/zstuCMdHsKx8Wr9ERZx9Kw/Login-updates-(passkey%2C-MFA%2C-org-links)?node-id=235-5730&node-type=frame&t=GzhBGn7sxcZeBrJj-11

**Comment by natalian98** [comment]
@edlerd could you add it to your backlog? thank you
