### ISSUE TITLE
Redirected to password reset after adding a security key

### ISSUE THREAD

**Issue by lukasSerelis** [canonical/identity-platform-login-ui#326]
After adding a security key I get redirected to reset password form.

Should bring me to success page.

Current flow:
Go to security key page -> Add security key -> Do the confirmation using security key device -> Get taken to reset password screen

Desired flow:
Go to security key page -> Add security key -> Do the confirmation using security key device -> Success screen

**Comment by natalian98** [comment]
Thanks for reporting the issue, we'll keep track of it in https://github.com/canonical/identity-platform-login-ui/issues/318 to preserve conversation history
