### ISSUE TITLE
UI for Security keys

### ISSUE THREAD

**Issue by lukasSerelis** [canonical/identity-platform-login-ui#327]
UI fixes for security keys screen.

Current
![image](https://github.com/user-attachments/assets/63798cd7-920d-4560-8b47-ff10eb4c0b47)

Desired
![image](https://github.com/user-attachments/assets/c4ca01b6-b7aa-465b-abb1-655c00eb01f3)
https://www.figma.com/design/zstuCMdHsKx8Wr9ERZx9Kw/Login-updates-(passkey%2C-MFA%2C-org-links)?node-id=235-19679&node-type=symbol&t=GzhBGn7sxcZeBrJj-11

Desired empty state (when no security keys have been added)
![image](https://github.com/user-attachments/assets/9e319d4b-5672-433b-a774-7764e1dd17f0)
https://www.figma.com/design/zstuCMdHsKx8Wr9ERZx9Kw/Login-updates-(passkey%2C-MFA%2C-org-links)?node-id=235-21367&node-type=instance&t=GzhBGn7sxcZeBrJj-11

Outside of visual, deleting a security key shouldn't re-render the entire screen. Should only add a spinner over security key list and disable the buttons.

Current
![image](https://github.com/user-attachments/assets/5792fb50-63ab-4912-ac5e-525ce18f7ff8)

Desired
![image](https://github.com/user-attachments/assets/1e55380c-e4e5-45b2-b508-a3450d4f0328)
https://www.figma.com/design/zstuCMdHsKx8Wr9ERZx9Kw/Login-updates-(passkey%2C-MFA%2C-org-links)?node-id=235-21711&node-type=instance&t=GzhBGn7sxcZeBrJj-11

Also success screen should give options to go back to managing security keys  
![image](https://github.com/user-attachments/assets/a26c2901-6e25-4688-83c2-e2e9e9941597)
https://www.figma.com/design/zstuCMdHsKx8Wr9ERZx9Kw/Login-updates-(passkey%2C-MFA%2C-org-links)?node-id=235-16304&node-type=frame&t=GzhBGn7sxcZeBrJj-11

**Comment by edlerd** [comment]
Thank you for posting the issue @lukasSerelis 

All display related issues with the setup flow should be resolved in #362 

For the interaction after the setup, the backend is sending a wrong redirect location:

![image](https://github.com/user-attachments/assets/1ecf3b43-6b2c-434c-9a33-7d432a22ad83)

![image](https://github.com/user-attachments/assets/d40dd8b1-3a0d-4904-a26d-5ebaa9ccecd1)

@natalian98 @shipperizer @BarcoMasile please fix the redirect location after passkey setup. After adding a new passkey, the response always redirects to the reset password flow. This should be the case for an initial signup where the user needs to change their password. But for a user already signed up correctly, this should be a passkey completion screen. I think we do not have a url for this yet, suggesting `setup_passkey_complete` as a new url.
