### ISSUE TITLE
`login_challenge` not created when user attempts to sign in directly in login ui

### ISSUE THREAD

**Issue by natalian98** [canonical/identity-platform-login-ui#329]
If you go directly to the login page `https://iam.dev.canonical.com/stg-identity-jaas-dev-login-ui/ui/login` without going through a hydra client first (e.g. grafana), there is no login challenge created.
This causes any login attempt to fail: after providing password and totp code, login ui displays an error:
![image](https://github.com/user-attachments/assets/7dc3ab85-3d18-4b24-aa1b-d9bb840e2246)

```
https://iam.dev.canonical.com/stg-identity-jaas-dev-login-ui/api/kratos/self-service/errors?id=undefined
"Error when getting flow error: 404 Not Found"
```
That is because the call to `/self-service/login/browser` should include the `login_challenge` parameter.

We should fix the flow logic for when the user attempts to log in directly in login ui to enable users to manage their account settings.
Note: this error can also be reproduced in a local dev setup, so recent changes haven't fixed it.

**Comment by BarcoMasile** [comment]
Food for thought: we could probably treat the "self service" as an indipendnet hydra client and in case of direct access to Login UI we could infer the user's trying to access through that self service hydra client.
