### ISSUE TITLE
Backup code generation from notification "Running out of backup codes" incorrect redirect

### ISSUE THREAD

**Issue by lukasSerelis** [canonical/identity-platform-login-ui#333]
When a user is generating new backup codes from the flow of "You just used a backup code, would you like to generate new codes" 
![image](https://github.com/user-attachments/assets/ccac668e-fb38-4449-9c11-ed7abbbe0192)

After generating the codes, a user is redirected to this screen, rather then redirecting to the resource a user logged in 
![image](https://github.com/user-attachments/assets/d53bf32f-fd51-4027-b4c7-7af0c044da62)

Ideally, in this case, we should validate that new backup codes have been setup, and redirect the user to the resource they were trying to access.
![image](https://github.com/user-attachments/assets/401cd670-855f-4454-9575-f7b1c877e96d)

**Comment by natalian98** [comment]
Hi @lukasSerelis, thanks for reporting the bug.
We have fixed it in https://github.com/canonical/identity-platform-login-ui/pull/317 and https://github.com/canonical/identity-platform-login-ui/pull/321, but it was not yet released on the ps6 dev environment. I'll upgrade it today.

**Comment by natalian98** [comment]
The deployment was upgraded, can you try reproducing the issue again?

**Comment by lukasSerelis** [comment]
Working now - now issues!
