### ISSUE TITLE
Token refresh is broken

### ISSUE THREAD

**Issue by nsklikas** [canonical/identity-platform-login-ui#373]
With the changes introduced to https://github.com/canonical/identity-platform-login-ui/pull/250, it looks like token refresh is broken. The reason is https://github.com/ory/fosite/blob/master/handler/oauth2/flow_refresh.go#L92:

Fosite tries to match the granted audience against the client's audience and that fails. We need to reverse the changes from https://github.com/canonical/identity-platform-login-ui/pull/250 and find another way to address the issue.

**Comment by BarcoMasile** [comment]
@nsklikas How about we just go back to asking for the audience in the original request?
It's acceptable if it fixes the issue, so we don't have to reverse 250

**Comment by nsklikas** [comment]
That's not the problem, the problem is that the audience may not be allowed for the client. Perhaps we could push for a change in fosite (I think that it is a valid assumption that the `client_id` should be automatically included in the client's `aud` list).

Refreshing a token works if you add the client_id to the client's allowed `aud`s. The problem is that when we add the client_id to the access token `aud`, we don't check if we are allowed to do that.

**Comment by nsklikas** [comment]
After discussing it with @BarcoMasile we decided that we should reverse https://github.com/canonical/identity-platform-login-ui/pull/250/commits/20fed796d51fff3689ea169e8fddb58c0dfcb5f3 and re-add the login in the admin UI to request for the client_id in the audience.
